- id: '1592579460084'
  alias: Georgia light on
  description: ''
  trigger:
  - device_id: 6965d327b99f4acd96d1375a50b30a89
    domain: hue
    platform: device
    subtype: turn_on
    type: remote_button_short_release
  condition: []
  action:
  - data:
      group_name: Georgias Room
      scene_name: Bright
    service: hue.hue_activate_scene
- id: '1592580522892'
  alias: Georgia light dim up
  description: ''
  trigger:
  - device_id: 6965d327b99f4acd96d1375a50b30a89
    domain: hue
    platform: device
    subtype: dim_up
    type: remote_button_short_release
  condition: []
  action:
  - data:
      brightness_step_pct: 10
    entity_id: light.georgias_room
    service: light.turn_on
- id: '1592582727099'
  alias: Georgia light dim down
  description: ''
  trigger:
  - device_id: 6965d327b99f4acd96d1375a50b30a89
    domain: hue
    platform: device
    subtype: dim_down
    type: remote_button_short_release
  condition: []
  action:
  - data:
      brightness_step_pct: -10
    entity_id: light.georgias_room
    service: light.turn_on
- id: '1592582770245'
  alias: Georgia light off
  description: ''
  trigger:
  - device_id: 6965d327b99f4acd96d1375a50b30a89
    domain: hue
    platform: device
    subtype: turn_off
    type: remote_button_short_release
  condition: []
  action:
  - data: {}
    entity_id: light.georgias_room
    service: light.turn_off
