# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

frontend:
  themes: !include themes.yaml
  javascript_version: latest

lovelace:
  mode: yaml
  resources: !include lovelace/resources.yaml

homeassistant:
  customize: !include customize.yaml

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
http:
  ssl_certificate: !secret html_ssl_certificate
  ssl_key: !secret html_ssl_key

duckdns:
  domain: !secret dns_domain
  access_token: !secret dns_access_token

# Text to speech
tts:
  - platform: google_translate

ifttt:
  key: !secret ifttt_key

evohome:
  username: !secret evohome_username
  password: !secret evohome_password
  scan_interval: 180

asuswrt:
  # Should probably make this use SSH instead.
  host: !secret asuswrt_host
  username: !secret asuswrt_username
  password: !secret asuswrt_password

mobile_app:

discovery:
  ignore:
  enable:

#blank host for auto discovery
remote:
  - platform: harmony
    name: Living room
    host: !secret harmony_host
    activity: Freeview

# we still need this integration so that we can use groups.
# make sure to use the integration without the 'ignore' next to it in integrations, otherwise it will use auto discovery and not work.
hue:
  bridges:
    - host: !secret hue_host
      allow_unreachable: true
      allow_hue_groups: true

python_script:

google:
  client_id: !secret google_calendar_client_id
  client_secret: !secret google_calendar_client_secret

recorder:
  db_url: !secret mariadb_connection_string
  exclude:
    entities:
      - sensor.time      
      - sensor.date
      - sensor.date_time
      - sensor.date_time_iso
      - sensor.internet_time
      - sensor.time_date
      - sensor.time_utc

influxdb:
  host: !secret influxdb_host
  port: !secret influxdb_port
  database: !secret influxdb_database
  username: !secret influxdb_username
  password: !secret influxdb_password
  max_retries: 3
  default_measurement: state

input_datetime: !include input_datetime.yaml
input_boolean: !include input_boolean.yaml
group: !include groups.yaml
person: !include people.yaml
device_tracker: !include device_tracker.yaml
automation: !include automations.yaml
automation old: !include_dir_merge_list automation/
script: !include_dir_merge_named scripts/
zone: !include zones.yaml
sensor: !include_dir_merge_list sensors/
climate: !include climate.yaml
notify: !include notify.yaml
light: !include light.yaml
timer: !include timers.yaml
