# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

frontend:
  themes: !include themes.yaml
  javascript_version: latest

lovelace:
  mode: yaml

homeassistant:
  customize: !include customize.yaml

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
http:
  ssl_certificate: !secret html_ssl_certificate
  ssl_key: !secret html_ssl_key

duckdns:
  domain: !secret dns_domain
  access_token: !secret dns_access_token

# Text to speech
tts:
  - platform: google_translate

ifttt:
  key: !secret ifttt_key

evohome:
  username: !secret evohome_username
  password: !secret evohome_password
  scan_interval: 180

asuswrt:
  # Should probably make this use SSH instead.
  host: !secret asuswrt_host
  username: !secret asuswrt_username
  password: !secret asuswrt_password

mobile_app:

discovery:
  ignore:
  enable:

#blank host for auto discovery
remote:
  - platform: harmony
    name: Living room
    host: !secret harmony_host
    activity: Freeview

hue:
  bridges:
    - host: !secret hue_host
      allow_unreachable: true
      allow_hue_groups: true

python_script:

google:
  client_id: !secret google_calendar_client_id
  client_secret: !secret google_calendar_client_secret

input_datetime: !include input_datetime.yaml
input_boolean: !include input_boolean.yaml
group: !include groups.yaml
person: !include people.yaml
device_tracker: !include device_tracker.yaml
automation: !include_dir_merge_list automation/
script: !include_dir_merge_named scripts/
zone: !include zones.yaml
sensor: !include_dir_merge_list sensors/
climate: !include climate.yaml
notify: !include notify.yaml
light: !include light.yaml
timer: !include timers.yaml
