
# Loads default set of integrations. Do not remove.
default_config:

evohome:
  username: !secret evohome_username
  password: !secret evohome_password

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
