# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# logger:
#   default: debug

frontend:
  themes: !include themes.yaml

lovelace:
  mode: yaml

homeassistant:
  customize: !include customize.yaml

# Text to speech
tts:
  - platform: google_translate

ifttt:
  key: !secret ifttt_key

evohome:
  username: !secret evohome_username
  password: !secret evohome_password
  scan_interval: 180

mobile_app:

discovery:
  ignore:
  enable:

# we still need this integration so that we can use groups.
# make sure to use the integration without the 'ignore' next to it in integrations, otherwise it will use auto discovery and not work.
hue:
  bridges:
    - host: !secret hue_host
      allow_unreachable: true
      allow_hue_groups: true

python_script:

recorder:
  db_url: !secret mariadb_connection_string
  exclude:
    entities:
      - sensor.time      
      - sensor.date
      - sensor.date_time
      - sensor.date_time_iso
      - sensor.internet_time
      - sensor.time_date
      - sensor.time_utc

influxdb:
  host: !secret influxdb_host
  port: !secret influxdb_port
  database: !secret influxdb_database
  username: !secret influxdb_username
  password: !secret influxdb_password
  max_retries: 3
  default_measurement: state

input_datetime: !include input_datetime.yaml
input_boolean: !include input_boolean.yaml
group: !include groups.yaml
person: !include people.yaml
automation: !include automations.yaml
automation manual: !include_dir_merge_list automation/
script: !include_dir_merge_named scripts/
zone: !include zones.yaml
sensor: !include_dir_merge_list sensors/
template: !include_dir_merge_list templates/
climate: !include climate.yaml
notify: !include notify.yaml
light: !include light.yaml
timer: !include timers.yaml
