- platform: asuswrt
  host: !secret asuswrt_host
  username: !secret asuswrt_username
  password: !secret asuswrt_password
  new_device_defaults:
    track_new_devices: false
    hide_if_away: false

- platform: huesensor

# - platform: tile
#   username: !secret tile_username
#   password: !secret tile_password
#   show_inactive: false
#   monitored_variables: 
#     - TILE