button_card_templates: !include /config/lovelace/templates.yaml

title: Home

custom_header:
  compact_mode: true

views:
  - !include /config/lovelace/view_home.yaml
  - !include /config/lovelace/view_rooms.yaml
  - !include /config/lovelace/view_heating.yaml
  - !include /config/lovelace/view_remote_control.yaml
