button_card_templates: !include /config/lovelace/templates.yaml

title: Home
resources:
  - url: /local/custom-cards/button-card.js?v=3.3.6
    type: module
  - url: /local/custom-cards/custom-header.js?v=1.5.8
    type: module
  - url: /local/custom-cards/simple-thermostat.js?v=0.35.0
    type: module
  - url: /local/custom-cards/atomic_calendar.js?v=0.8.9
    type: module

custom_header:
  compact_mode: true

views:
  - !include /config/lovelace/view_home.yaml
  - !include /config/lovelace/view_rooms.yaml
  - !include /config/lovelace/view_heating.yaml
  - !include /config/lovelace/view_remote_control.yaml
