button_card_templates: !include /config/lovelace/templates.yaml

title: Home
resources:
  - url: /local/custom-cards/button-card.js?v=2.0.5
    type: module
  - url: /local/custom-cards/compact-custom-header.js?v=1.3.6
    type: module
  - url: /local/custom-cards/simple-thermostat.js?v=0.26.0
    type: module
  - url: /local/custom-cards/simple-weather-card-bundle.js?v=0.5.0
    type: module
  - url: /local/custom-cards/atomic_calendar.js?v=0.8.5
    type: module

cch:
  options: clock
  compact_header: true
  clock_format: 24
  clock_date: true
  swipe: true

views:
  - !include /config/lovelace/view_home.yaml
  - !include /config/lovelace/view_rooms.yaml
  - !include /config/lovelace/view_heating.yaml
  - !include /config/lovelace/view_remote_control.yaml
