button_card_templates: !include /config/lovelace/templates.yaml

title: Home
resources:
  - url: /local/custom-cards/button-card.js
    type: module
views:
  - !include /config/lovelace/view_home.yaml
  - !include /config/lovelace/view_downstairs.yaml
  - !include /config/lovelace/view_upstairs.yaml