## octopus go rest template ##

- platform: rest
  name: Gas Half Hourly
  resource: !secret octopus_gas_api
  headers:
    Authorization: !secret octopus_auth
  params:
    period_from: "{{ (now() - timedelta(days = 1) - timedelta(minutes = 15)).isoformat() }}"
    period_to: "{{ (now() - timedelta(days = 1) + timedelta(minutes = 15)).isoformat() }}"
  value_template: >-
    {% set calorific_value = 39.7%}
    {% set volume_correction_value = 1.02264 %}
    {{ ((value_json.results|sum(attribute='consumption')|float) * volume_correction_value * calorific_value) / 3.6|round(3) }}
  scan_interval: 1800
  unit_of_measurement: 'kWh'
  device_class: energy
  state_class: total
  json_attributes:
    - "results"

- platform: rest
  name: Gas Daily
  resource: !secret octopus_gas_api
  headers:
    Authorization: !secret octopus_auth
  params:
    period_from: "{{ (as_timestamp(now() - timedelta(days = 1))|timestamp_custom('%Y-%m-%d')) + 'T00:00:00' }}"
    period_to: "{{ (now() - timedelta(days = 1)).isoformat() }}"
  value_template: >-
    {% set calorific_value = 39.7%}
    {% set volume_correction_value = 1.02264 %}
    {{ ((value_json.results|sum(attribute='consumption')|float) * volume_correction_value * calorific_value) / 3.6|round(3) }}
  scan_interval: 1800
  unit_of_measurement: 'kWh'
  device_class: energy
  state_class: total
  json_attributes:
    - "results"

- platform: rest
  name: Electricity Daily Peak
  resource: !secret octopus_electricity_api
  headers:
    Authorization: !secret octopus_auth
  params:
    period_from: "{{ (as_timestamp(now() - timedelta(days = 1))|timestamp_custom('%Y-%m-%d')) + 'T00:00:00' }}"
    period_to: "{{ (now() - timedelta(days = 1)).isoformat() }}"
  value_template: >-
    {% set ns = namespace(total=0) %}
    {% for res in value_json.results %}
      {% set time = as_timestamp(res.interval_start)|timestamp_custom('%H:%M:%S') %}
      {% if time < '00:30:00' or time >= '04:30:00' %}
        {% set ns.total = ns.total + res.consumption %}
      {% endif %}      
    {% endfor %}
    {{ (ns.total|round(3)) }}
  scan_interval: 1800
  unit_of_measurement: 'kWh'
  device_class: energy
  state_class: total
  json_attributes:
    - "results"

- platform: rest
  name: Electricity Daily Off Peak
  resource: !secret octopus_electricity_api
  headers:
    Authorization: !secret octopus_auth
  params:
    period_from: "{{ (as_timestamp(now() - timedelta(days = 1))|timestamp_custom('%Y-%m-%d')) + 'T00:00:00' }}"
    period_to: "{{ (now() - timedelta(days = 1)).isoformat() }}"
  value_template: >-
    {% set ns = namespace(total=0) %}
    {% for res in value_json.results %}
      {% set time = as_timestamp(res.interval_start)|timestamp_custom('%H:%M:%S') %}
      {% if '00:30:00' <= time < '04:30:00' %}
        {% set ns.total = ns.total + res.consumption %}
      {% endif %}      
    {% endfor %}
    {{ (ns.total|round(3)) }}
  scan_interval: 1800
  unit_of_measurement: 'kWh'
  device_class: energy
  state_class: total
  json_attributes:
    - "results"

- platform: rest
  name: Electricity Half Hourly
  resource: !secret octopus_electricity_api
  headers:
    Authorization: !secret octopus_auth
  params:
    period_from: "{{ (now() - timedelta(days = 1) - timedelta(minutes = 15)).isoformat() }}"
    period_to: "{{ (now() - timedelta(days = 1) + timedelta(minutes = 15)).isoformat() }}"
  value_template: "{{ value_json.results|sum(attribute='consumption')|round(3) }}"
  scan_interval: 1800
  unit_of_measurement: 'kWh'
  device_class: energy
  state_class: total
  json_attributes:
    - "results"

- platform: rest
  name: Electricity Total
  resource: !secret octopus_electricity_api
  headers:
    Authorization: !secret octopus_auth
  params:
    period_from: "{{ as_timestamp(now() - timedelta(days = 1))|timestamp_custom('%Y-%m-%d') + 'T00:00:00' }}"
    period_to: "{{ as_timestamp(now() - timedelta(days = 1))|timestamp_custom('%Y-%m-%d') + 'T23:59:59' }}"
  value_template: >-
    {% if value_json.results is defined and value_json.results|count == 48 %}
      {{ value_json.results|sum(attribute='consumption')|round(3) }}
    {% else %}
      0
    {% endif %}
  scan_interval: 1800
  unit_of_measurement: kWh
  device_class: energy
  state_class: total
  json_attributes:
    - "results"

- platform: rest
  name: Gas Total
  resource: !secret octopus_gas_api
  headers:
    Authorization: !secret octopus_auth
  params:
    period_from: "{{ as_timestamp(now() - timedelta(days = 1))|timestamp_custom('%Y-%m-%d') + 'T00:00:00' }}"
    period_to: "{{ as_timestamp(now() - timedelta(days = 1))|timestamp_custom('%Y-%m-%d') + 'T23:59:59' }}"
  value_template: >-
    {% set calorific_value = 39.7%}
    {% set volume_correction_value = 1.02264 %}
    {% if value_json.results is defined and value_json.results|count == 48 %}
      {{ (((value_json.results|sum(attribute='consumption')|float) * volume_correction_value * calorific_value) / 3.6)|round(3) }}
    {% else %}
      0
    {% endif %}
  scan_interval: 1800
  unit_of_measurement: kWh
  device_class: energy
  state_class: total
  json_attributes:
    - "results"