# Sensor for ssl-cert check to see how many days left.
- platform: command_line
  name: SSL cert expiry
  unit_of_measurement: days
  scan_interval: 10800
  command: !secret sensor_ssl_expiry_command
