- alias: "Cathy leaving work"
  trigger:
    - platform: zone
      entity_id: person.cathy_nealon
      zone: zone.north_tees_nhs
      event: leave
    - platform: zone
      entity_id: person.cathy_nealon
      zone: zone.redcar_nhs
      event: leave
  condition:
    condition: state
    entity_id: sensor.cathys_iphone_battery_state
    state: "Charging"
  action:
    service: script.notify_person
    data:
      device: "ios_bens_iphone"
      title: "Work"
      message: "Cathy's leaving"

- alias: "Ben leaving work"
  trigger:
    platform: zone
    entity_id: person.ben_nealon
    zone: zone.amplience
    event: leave
  condition:
    condition: state
    entity_id: sensor.ben_s_iphone_battery_state
    state: "Charging"
  action:
    service: script.notify_person
    data:
      device: "ios_cathys_iphone"
      title: "Work"
      message: "Ben's leaving"

- alias: "Cathy home"
  trigger:
    platform: zone
    entity_id: person.cathy_nealon
    zone: zone.home
    event: enter
  action:
    service: script.notify_person
    data:
      device: "ios_bens_iphone"
      title: "Home"
      message: "Cathy arrived"

- alias: "Ben home"
  trigger:
    platform: zone
    entity_id: person.ben_nealon
    zone: zone.home
    event: enter
  action:
    service: script.notify_person
    data:
      device: "ios_cathys_iphone"
      title: "Home"
      message: "Ben arrived"

- alias: "Last person leaves home"
  trigger:
    platform: state
    entity_id: group.household
    from: "home"
  action:
    service: script.notify_person
    data:
      device: "ios_bens_iphone"
      title: "Home"
      message: "Everyone's left"

- alias: "First person arrived home"
  trigger:
    platform: state
    entity_id: group.household
    to: "home"
  action:
    service: script.notify_person
    data:
      device: "ios_bens_iphone"
      title: "Home"
      message: "First person arrived"
