- alias: "Cathy leaving work"
  trigger:
    - platform: zone
      entity_id: person.cathy_nealon
      zone: zone.south_tees_nhs
      event: leave
  action:
    service: script.notify_person
    data:
      device: "bens_iphone"
      title: "Work"
      message: "Cathy's leaving"

- alias: "Ben leaving work"
  trigger:
    platform: zone
    entity_id: person.ben_nealon
    zone: zone.amplience
    event: leave
  action:
    service: script.notify_person
    data:
      device: "cathys_iphone"
      title: "Work"
      message: "Ben's leaving"

- alias: "Cathy home"
  trigger:
    platform: zone
    entity_id: person.cathy_nealon
    zone: zone.home
    event: enter
  action:
    service: script.notify_person
    data:
      device: "bens_iphone"
      title: "Home"
      message: "Cathy arrived"

- alias: "Ben home"
  trigger:
    platform: zone
    entity_id: person.ben_nealon
    zone: zone.home
    event: enter
  action:
    service: script.notify_person
    data:
      device: "cathys_iphone"
      title: "Home"
      message: "Ben arrived"

- alias: "Last person leaves home"
  trigger:
    platform: state
    entity_id: group.household
    from: "home"
  action:
    # notify
    - service: script.notify_person
      data:
        device: "bens_iphone"
        title: "Home"
        message: "Everyone's left"
      # turn off all switches, not specifying an entity does all
    - service: switch.turn_off
      data:
        entity_id: group.switches_geofencing
      # turn off TV
    - service: remote.turn_off
      data:
        entity_id: remote.living_room
      # Heating into away mode.
    - service: climate.set_preset_mode
      data:
        entity_id: climate.home
        preset_mode: away
      # all lights off, excluding hallway.
    - service: light.turn_off
      data:
        entity_id: light.all_excluding
      # notify IFTTT
    - service: ifttt.trigger
      data:
        event: "heatmiser_away"
      # reset the livingroom motion sensor enabled flag: so that the lights turn off on their own.
    - service: input_boolean.turn_on
      data:
        entity_id: input_boolean.livingroom_motion_enabled

- alias: "First person arrived home"
  trigger:
    platform: state
    entity_id: group.household
    to: "home"
  action:
    # notify
    - service: script.notify_person
      data:
        device: "bens_iphone"
        title: "Home"
        message: "First person arrived"
    # reset heating out of away mode
    - service: climate.set_preset_mode
      data:
        entity_id: climate.home
        preset_mode: Reset
    # notify IFTTT
    - service: ifttt.trigger
      data:
        event: "heatmiser_home"
