- alias: "Hot water too low"
  trigger:
    platform: numeric_state
    entity_id: water_heater.dhw_controller
    value_template: "{{ state_attr('water_heater.dhw_controller', 'current_temperature') }}"
    below: 30
  condition:
    condition: state
    entity_id: water_heater.dhw_controller
    state: "off"
  action:
    service: script.notify_household
    data:
      title: "Hot Water"
      message: "Temperature too low: {{ state_attr('water_heater.dhw_controller', 'current_temperature') }} degrees"
