- alias: "Tumble dryer finished, notifying and starting timer"
  trigger:
    platform: numeric_state
    entity_id: sensor.tumble_dryer_current
    below: 0.5
    for: "00:01:00"
  condition:
    condition: state
    entity_id: switch.tumble_dryer
    state: "on"
  action:
  # cancel any pre-existing.
    - service: timer.cancel
      data_template:
        entity_id: timer.tumble_dryer
    - service: timer.start
      data_template:
        entity_id: timer.tumble_dryer
        duration: '00:30:00'
    - service: script.notify_household
      data:
        title: "Tumble Dryer"
        message: "I'm finished!"

- alias: "Tumble dryer started"
  trigger:
    platform: numeric_state
    entity_id: sensor.tumble_dryer_current
    above: 0.5
  condition:
    condition: state
    entity_id: switch.tumble_dryer
    state: "on"
  action:
    - service: timer.cancel
      data_template:
        entity_id: timer.tumble_dryer

- alias: "Tumble dryer timer finished, turning off"
# Tumble dryer timer finished
# Turn off
  trigger:
    platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.tumble_dryer
  action:
    - service: switch.turn_off
      data:
        entity_id: switch.tumble_dryer

- alias: "Washing machine finished notification, start nag timer"
  trigger:
    platform: numeric_state
    entity_id: sensor.washing_machine_current
    below: 0.055
    for: "00:01:00"
  condition:
    condition: state
    entity_id: switch.washing_machine
    state: "on"
  action:
  # cancel any pre-existing.
    - service: timer.cancel
      data_template:
        entity_id: timer.washing_machine
    - service: timer.start
      data_template:
        entity_id: timer.washing_machine
        duration: '00:30:00'
    - service: script.notify_household
      data:
        title: "Washing Machine"
        message: "I'm finished!"

- alias: "Washing machine started"
  trigger:
    platform: numeric_state
    entity_id: sensor.washing_machine_current
    above: 0.055
  condition:
    condition: state
    entity_id: switch.washing_machine
    state: "on"
  action:
    - service: timer.cancel
      data_template:
        entity_id: timer.washing_machine

- alias: "Washing machine timer finished, did you empty me?"
# washing machine timer finished
# Nag household to empty me
  trigger:
    platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.washing_machine
  action:
    - service: script.notify_household
      data:
        title: "Washing Machine"
        message: "Did you empty Me?"

- alias: "Kettle finished, turning off"
  initial_state: false
  trigger:
    platform: numeric_state
    entity_id: sensor.kettle_current
    below: 0.5
    for: "00:00:10"
  condition:
    condition: state
    entity_id: switch.kettle
    state: "on"
  action:
  # cancel any pre-existing.
    - service: switch.turn_off
      data:
        entity_id: switch.kettle

- alias: "Georgia fairy lights on"
  initial_state: false
  trigger:
    platform: state
    entity_id: switch.georgia_fairy_lights
    from: "off"
    to: "on"
  action:
  # cancel any pre-existing.
    - service: timer.cancel
      data_template:
        entity_id: timer.georgia_fairy_lights
    - service: timer.start
      data_template:
        entity_id: timer.georgia_fairy_lights
        duration: '01:00:00'

- alias: "Georgia fairy lights off"
  # switch goes off, cancel any timer.
  initial_state: false
  trigger:
    platform: state
    entity_id: switch.georgia_fairy_lights
    to: "off"
  action:
  # cancel any pre-existing.
    - service: timer.cancel
      data_template:
        entity_id: timer.georgia_fairy_lights

- alias: "Georgia fairy lights timer finished, turning off"
# fairy lights timer finished
# Turn off
  initial_state: false
  trigger:
    platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.georgia_fairy_lights
  action:
    - service: switch.turn_off
      data:
        entity_id: switch.georgia_fairy_lights