- alias: "Tumble dryer finished"
  trigger:
    platform: numeric_state
    entity_id: switch.tumble_dryer
    value_template: "{{ state_attr('switch.tumble_dryer', 'current_a') }}"
    below: 0.5
    for: "00:01:00"
  condition:
    condition: state
    entity_id: switch.tumble_dryer
    state: "on"
  action:
    service: script.notify_household
    data:
      title: "Tumble Dryer"
      message: "I'm finished!"
