- alias: "Auto Renew SSL Cert"
  trigger:
    platform: numeric_state
    entity_id: sensor.ssl_cert_expiry
    below: 29
  action:
    service: shell_command.renew_ssl

- alias: "SSL expiry notification"
  trigger:
    platform: numeric_state
    entity_id: sensor.ssl_cert_expiry
    below: 21
  action:
    service: notify.ios_bens_iphone
    data:
      title: "SSL Certificate"
      message: "Expires in 21 days and has not been automatically renewed"
