- alias: 'Set HA theme for day and night'
  trigger:
    - platform: homeassistant
      event: start
    - platform: state
      entity_id: sun.sun
      to: above_horizon
    - platform: state
      entity_id: sun.sun
      to: below_horizon
  action:
    - service: frontend.set_theme
      data_template:
        name: >
          {% if is_state('states.sun.sun', 'above_horizon') %}
            clear
          {% else %}
            darkcyan
          {% endif %}